name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.1
    - name: Set up conan default profile
      run: conan profile new default --detect
    - name: Configure conan profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Install dependencies
      run: conan install .
    - name: CMake
      run: cmake .
    - name: Build
      run: make
